cmd injection fixes by quoting user input
phylum-dev/phylum-ci pull request #133
Opened 2022-10-04 05:51 UTC by h4sh5

Many subprocess cmd executions in phylum-ci do not escape user input either via lockfile path, branch name or environment variables before executing, leading to potential command injection vulnerabilities.

This PR adds shlex.quote to the instances I could find, but might not be exhaustive.

2022-10-04 05:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/phylum-dev/phylum-ci?pullRequest=133) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/phylum-dev/phylum-ci?pullRequest=133) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/phylum-dev/phylum-ci?pullRequest=133) it.</sub>

2022-10-04 18:29 UTC, maxrake requested changes
It is not clear whether the intent of this PR is to correct for _potential_ command injection attacks that _could_ occur in the future, given a change in the way the `subprocess.run` function is called. Or, if there are current vulnerabilities present that require remediation.

The `phylum-ci` code base does not contain any instances of `subprocess.run` called with `shell=True`. Therefore, the assertion is there are not currently any shell injection vulnerabilities. The severity/impact of the remaining unsanitized input is low since the worst it can do is cause command execution failures and tracebacks to be printed in the output/logs.

There may still be some merit in this PR, to sanitize the input that comes from environment variables. It also might be fruitful to create an issue to discuss this further.

If this PR is to be pursued, then it will need to account for all the files and instances of `subprocess.run`. Additionally, the CLA will need to be signed and at least one semantic PR will be required to pass the CI check, as outlined in the ["Pull Request Guidelines"](https://github.com/phylum-dev/phylum-ci/blob/main/CONTRIBUTING.md#pull-request-guidelines) section of the `CONTRIBUTING.md` file.

References:
* The Python docs for `subprocess`, specifically the [security considerations](https://docs.python.org/3/library/subprocess.html#security-considerations)
  > If the shell is invoked explicitly, via shell=True, it is the application’s responsibility to ensure that all whitespace and metacharacters are quoted appropriately to avoid [shell injection](https://en.wikipedia.org/wiki/Shell_injection#Shell_injection) vulnerabilities.
* The [`bandit` tool check B603: subprocess_without_shell_equals_true](https://bandit.readthedocs.io/en/latest/plugins/b603_subprocess_without_shell_equals_true.html)
  > ...spawning of a subprocess without the use of a command shell. This type of subprocess invocation is not vulnerable to shell injection attacks, but care should still be taken to ensure validity of input.
* A warning about using `shlex.quote` [from the Python docs](https://docs.python.org/3/library/shlex.html#shlex-quote-warning)
  > Warning The shlex module is only designed for Unix shells.
The [quote()](https://docs.python.org/3/library/shlex.html#shlex.quote) function is not guaranteed to be correct on non-POSIX compliant shells or shells from other operating systems such as Windows. Executing commands quoted by this module on such shells can open up the possibility of a command injection vulnerability. Consider using functions that pass command arguments with lists such as [subprocess.run()](https://docs.python.org/3/library/subprocess.html#subprocess.run) with shell=False.

2022-10-05 02:17 UTC, h4sh5 commented on src/phylum/ci/ci_github.py
> +        cmd = f"git config --global --add safe.directory {shlex.quote(github_workspace)}"
Agreed there. In terms of the git command, even if `shell=True` is not in subprocess.run, arbitrary code might still be executed using argument flags in git (such as the `--exec-path[=<path>]` option or by injecting configurations via `-c`  or `--config-env`

2022-10-14 04:05 UTC, maxrake commented
This PR will be closed in favor of #144, which was opened to complete the work started here.

2022-10-14 04:05 UTC, closed without merging