feat: extend GHA integration to support `pull_request_target` events
phylum-dev/phylum-ci pull request #341
Opened 2023-10-24 17:40 UTC by maxrake

This change makes it possible to use the GitHub Action (GHA) integration for PRs that originate from forks, by enabling workflows to run on the `pull_request_target` event. This change is simple enough, but comes with some heavy security considerations. In order for the GHA to run, a workflow using it will need to checkout the PRs code. This requires very careful attention so as not to allow so-called "pwn requests":

* https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
* https://blog.gitguardian.com/github-actions-security-cheat-sheet/

To that end, the documentation updates that go with this change will be explicit in their warnings about how to properly use the Phylum GHA in the most secure way possible. This effectively means the workflow should be limited to executing the bare minimum required for Phylum analysis.

Further, the Phylum analysis that does run will need to do so in a way that does not allow for arbitrary code execution. Therefore, this PR is intended to be held back until the Phylum CLI adds some additional protections around lockfile generation.

Closes #331

## Checklist

- [x] Does this PR have an associated issue (i.e., `closes #<issueNum>` in description above)?
- [x] Have you ensured that you have met the expected acceptance criteria?
- [x] Have you created sufficient tests?
  - Manual testing was performed with a fork of a personal repo
- [ ] Have you updated all affected documentation?
  - This will happen in a separate PR, in the [`phylum-analyze-pr-action` repository](https://github.com/phylum-dev/phylum-analyze-pr-action)

2023-10-24 17:42 UTC, maxrake commented on src/phylum/ci/ci_github.py
Commenting here as a way to remember to keep this PR open until the Phylum CLI changes are made...

The minimum Phylum CLI version constants will need to be updated in `src/phylum/constants.py` once there is a release out containing the lockfile generation security hardening.

2023-12-01 00:02 UTC, maxrake commented
The Dockerfile tests are going to fail until a non-release candidate of the Phylum CLI is released with a version greater than v5.9.0-rc2

2023-12-01 18:00 UTC, cd-work requested changes

2023-12-01 22:16 UTC, maxrake commented on src/phylum/ci/ci_base.py
> +        self.no_gen = False  # AKA disable_lockfile_generation
Fair. It was a feeble attempt to keep from expanding a handful of lines into multiple lines each. It has been changed.

2023-12-05 18:06 UTC, maxrake commented on src/phylum/ci/ci_github.py
The CLI changes were made and included in the v5.9.0 release. The Dockerfile tests are passing again.

2023-12-05 18:07 UTC, merged